# docker-compose.yml

version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_app_dev
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/todo_app_dev
    depends_on:
      - db
    volumes:
      - .:/app
    command: mix phx.server

volumes:
  db_data:
